id: PE1112C7E
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN9314
  title: རྒྱལ་སྲས་ཀྱི་སྤྱོད་ལ་འཇུག་པའི་ཆོས་སྐོར།
  volumes:
    c6f8545c8ba842e3873ecd9dd22188d2:
      image_group_id: I3CN9316
      title: ''
      base_file: v001.txt
  author: ''
